services:
  - type: web
    name: lectoryape-visualizer
    env: static
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html